import React from 'react';
import ReactDOM from 'react-dom/client';
import { AppProvider } from './context/AppContext';
import App from './App';
import './index.css';

// Register the Workbox service worker generated by vite-plugin-pwa.
// `autoUpdate` mode (set in vite.config.ts) means: when a new SW is
// available, it activates immediately on the next page navigation
// without prompting the user — ideal for training centres where
// users shouldn't have to manage updates manually.
import { registerSW } from 'virtual:pwa-register';

registerSW({
  immediate: true,
  onNeedRefresh() {
    // New content available — SW will auto-activate on next navigation
    // (autoUpdate strategy handles this without a UI prompt)
  },
  onOfflineReady() {
    console.log('[Sahakar Setu] App is ready to work offline.');
  },
  onRegistered(r) {
    // Check for SW updates every hour while the page is open
    r &&
      setInterval(
        () => {
          r.update();
        },
        60 * 60 * 1000,
      );
  },
  onRegisterError(error) {
    console.error('[Sahakar Setu] Service worker registration error:', error);
  },
});

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <AppProvider>
      <App />
    </AppProvider>
  </React.StrictMode>,
);
